### ISSUE TITLE
Transparency doesn't seem to work for me

### ISSUE THREAD

**Issue by RedDragonTix** [Dulappy/aero-window-manager#7] opened 2024-06-18 15:06 UTC
All I did was running either with PSTools or ExecTI and it changes titlebar color to white and no transparency, tried to set it to 1 in configuration but nothing, I'm using latest version

![image](https://github.com/Dulappy/aero-window-manager/assets/96621985/d6f24780-43b5-4e3a-bd40-8c1bbc80af39)

OS: Windows 10 LTSC 2021 IoT

**Comment by Dulappy** [comment] 2024-06-18 18:04
Change the color balance.

**Comment by IveMalfunctioned** [comment] 2024-06-18 19:30
why are you closing the issue? The problem is NOT resolved.

**Comment by RedDragonTix** [comment] 2024-06-18 19:34
> Change the color balance.

it didn't work

**Comment by Dulappy** [comment] 2024-06-19 14:23
Is AWM the only thing you're running that hooks into DWM? Are you sure your settings are being saved properly (this has been an issue)?

If yes to both, could you please attach a .reg file from `HKLM\SOFTWARE\AWM`?

**Comment by RedDragonTix** [comment] 2024-06-19 18:21
> Is AWM the only thing you're running that hooks into DWM? Are you sure your settings are being saved properly (this has been an issue)?
> 
> If yes to both, could you please attach a .reg file from `HKLM\SOFTWARE\AWM`?

Well, all I did was copy AWM files to C:\AWM, ran the command regsvr32 c:\awm\msdia140_awm.dll in cmd as administraor and then ran the Injector using PSTools or ExecTI

[AWM.zip](https://github.com/user-attachments/files/15904635/AWM.zip)

**Comment by Dulappy** [comment] 2024-06-19 18:28
The color balance is still at 100 for both active and inactive windows in the attached file. Lower it.

**Comment by RedDragonTix** [comment] 2024-06-19 19:56
> The color balance is still at 100 for both active and inactive windows in the attached file. Lower it.

I did lowered but rather it darkens the color and still no transparency

**Comment by Dulappy** [comment] 2024-06-19 20:01
Could you attach a screenshot?

**Comment by RedDragonTix** [comment] 2024-06-20 09:25
> Could you attach a screenshot?

![image](https://github.com/Dulappy/aero-window-manager/assets/96621985/e644e9c4-830e-446d-971e-92bc32ca58d2)
this happens
I lowered at 50

**Comment by Dulappy** [comment] 2024-06-20 15:22
Do not change the AccentPolicy value to anything but 0 unless you know what you're doing. This is what everything looks like with AccentPolicy set to 1:
![image](https://github.com/Dulappy/aero-window-manager/assets/92800639/afa85737-ac89-4680-95f3-8e1a68832078)

This is what everything looks like with AccentPolicy set to 0:
![image](https://github.com/Dulappy/aero-window-manager/assets/92800639/e6261891-e5f4-457a-9303-460cdbc41f41)

I'm sorry I did not catch the issue when you sent me the .reg file.

**Closed by Dulappy** 2024-06-20 15:22 UTC

**Comment by RedDragonTix** [comment] 2024-06-20 19:12
> Do not change the AccentPolicy value to anything but 0 unless you know what you're doing. This is what everything looks like with AccentPolicy set to 1: ![image](https://private-user-images.githubusercontent.com/92800639/341469696-afa85737-ac89-4680-95f3-8e1a68832078.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MTA5OTgsIm5iZiI6MTcxODkxMDY5OCwicGF0aCI6Ii85MjgwMDYzOS8zNDE0Njk2OTYtYWZhODU3MzctYWM4OS00NjgwLTk1ZjMtOGUxYTY4ODMyMDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE5MTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYTVlZmI5YjE0Njk4NTEyNjU3ZGQ3MTQwODQxM2UwNGMxZWZjYTBhYThmNGExNTBlNjdkZWI1ZjkxMmRiOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o5SeSAkqFWZaF2aky09ltqmsAJGauj6MlMQTb_wBLo8)
> 
> This is what everything looks like with AccentPolicy set to 0: ![image](https://private-user-images.githubusercontent.com/92800639/341470041-e6261891-e5f4-457a-9303-460cdbc41f41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MTA5OTgsIm5iZiI6MTcxODkxMDY5OCwicGF0aCI6Ii85MjgwMDYzOS8zNDE0NzAwNDEtZTYyNjE4OTEtZTVmNC00NTdhLTkzMDMtNDYwY2RiYzQxZjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE5MTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjQ0ZmE3ZGViMTA0MWNmNjlhMzgzMDFkNDE3N2VjMTAzODA0Zjc5MzYwNWFjNGRmNDc1OTM0NDcwOWFkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x7mBga19c2AcwZFgZ0WvxgvcVyfyhrR7fOTfCg0xvz8)
> 
> I'm sorry I did not catch the issue when you sent me the .reg file.

I got it fixed, finally transparency works, thanks man :)
